name: Build & Release Titan Index (sanity)

on:
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Say hello
        run: echo "release workflow syntax OK"
